### ISSUE TITLE
Wrong translation

### ISSUE THREAD

**Issue by GitRon** [Altai-man/kataba-fork#2]
https://github.com/Altai-man/kataba-fork/blob/master/wsgi/openshift/captcha/locale/de/LC_MESSAGES/django.po

The correct German is: "Ungültiges CAPTCHA" and "Dieses Feld wird benötigt."

Best,
Ron

**Comment by Altai-man** [comment]
Oh, thanks. But you should write about it to https://github.com/mbi/django-simple-captcha issue tracker, because I just use it as dependency in this fork and didn't write django-simple-captcha module myself.

**Comment by GitRon** [comment]
Alright, will do. Thanks :)

**Comment by Altai-man** [comment]
Thanks to you too, I'll close this issue. Do you really interested in this fork? If so, I recommend you to use Kasatou - less outdated project with similar goals. I forked Kataba a long time ago, so there is many weird and ugly code pieces.

**Comment by GitRon** [comment]
Sorry, no interest. I'm using the simple-captcha and wanted to find out why the translation is wrong. I just found your fork with google :)

**Comment by Altai-man** [comment]
It was my education project, so nothing wrong with it's uselessness. (: Thanks for issue anyway.

**Comment by GitRon** [comment]
Haha, alright :)
